#usability edits: Amina Li, UCSB 2022
#further usability edits: Sebastian Carron, CLU 2024

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, voltStep, voltStop, timeStep):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(898, 620)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 10, 151, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 30, 151, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lblBiasVoltage = QtGui.QLineEdit(self.centralwidget)
        self.lblBiasVoltage.setGeometry(QtCore.QRect(380, 10, 111, 20))
        self.lblBiasVoltage.setReadOnly(True)
        self.lblBiasVoltage.setObjectName(_fromUtf8("lblBiasVoltage"))
        self.lblCurrentMeasurement = QtGui.QLineEdit(self.centralwidget)
        self.lblCurrentMeasurement.setGeometry(QtCore.QRect(380, 30, 111, 20))
        self.lblCurrentMeasurement.setReadOnly(True)
        self.lblCurrentMeasurement.setObjectName(_fromUtf8("lblCurrentMeasurement"))
        self.btnSetVoltage = QtGui.QPushButton(self.centralwidget)
        self.btnSetVoltage.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.btnSetVoltage.setObjectName(_fromUtf8("btnSetVoltage"))
        self.sbSetVoltage = QtGui.QSpinBox(self.centralwidget)
        self.sbSetVoltage.setGeometry(QtCore.QRect(80, 10, 61, 22))
        self.sbSetVoltage.setMaximum(1100)
        self.sbSetVoltage.setSingleStep(5)
        self.sbSetVoltage.setObjectName(_fromUtf8("sbSetVoltage"))
        self.btnStepUp = QtGui.QPushButton(self.centralwidget)
        self.btnStepUp.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.btnStepUp.setObjectName(_fromUtf8("btnStepUp"))
        self.btnStepDown = QtGui.QPushButton(self.centralwidget)
        self.btnStepDown.setGeometry(QtCore.QRect(10, 79, 71, 21))
        self.btnStepDown.setObjectName(_fromUtf8("btnStepDown"))
        self.lblStepUp = QtGui.QLineEdit(self.centralwidget)
        self.lblStepUp.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.lblStepUp.setReadOnly(True)
        self.lblStepUp.setObjectName(_fromUtf8("lblStepUp"))
        self.lblStepDown = QtGui.QLineEdit(self.centralwidget)
        self.lblStepDown.setGeometry(QtCore.QRect(80, 80, 113, 20))
        self.lblStepDown.setReadOnly(True)
        self.lblStepDown.setObjectName(_fromUtf8("lblStepDown"))
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(11, 41, 86, 20))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.sbStepSize = QtGui.QSpinBox(self.centralwidget)
        self.sbStepSize.setGeometry(QtCore.QRect(95, 39, 91, 22))
        self.sbStepSize.setMaximum(25)  ###MAX VOLTAGE STEP SIZE HERE###
        self.sbStepSize.setProperty("value", voltStep)
        self.sbStepSize.setObjectName(_fromUtf8("sbStepSize"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 60, 151, 20))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.sbMeasurementInterval = QtGui.QSpinBox(self.centralwidget)
        self.sbMeasurementInterval.setGeometry(QtCore.QRect(380, 60, 111, 21))
        self.sbMeasurementInterval.setMinimum(1)
        self.sbMeasurementInterval.setMaximum(60)
        self.sbMeasurementInterval.setProperty("value", 1)
        self.sbMeasurementInterval.setObjectName(_fromUtf8("sbMeasurementInterval"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 431, 421))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlGraphLatestV = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlGraphLatestV.setObjectName(_fromUtf8("vlGraphLatestV"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 130, 431, 421))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlGraphAllV = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlGraphAllV.setObjectName(_fromUtf8("vlGraphAllV"))
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 80, 151, 20))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.sbPlotRefreshInterval = QtGui.QSpinBox(self.centralwidget)
        self.sbPlotRefreshInterval.setGeometry(QtCore.QRect(380, 80, 111, 22))
        self.sbPlotRefreshInterval.setMinimum(1)
        self.sbPlotRefreshInterval.setMaximum(60)
        self.sbPlotRefreshInterval.setProperty("value", 5)
        self.sbPlotRefreshInterval.setObjectName(_fromUtf8("sbPlotRefreshInterval"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 180, 201, 20))
        self.lineEdit_6.setDragEnabled(False)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(620, 180, 191, 20))
        self.lineEdit_7.setDragEnabled(False)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 550, 47, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 550, 47, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cbAutoStep = QtGui.QCheckBox(self.centralwidget)
        self.cbAutoStep.setGeometry(QtCore.QRect(530, 10, 16, 16))
        self.cbAutoStep.setText(_fromUtf8(""))
        self.cbAutoStep.setObjectName(_fromUtf8("cbAutoStep"))
        self.lineEdit_8 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(552, 11, 31, 20))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.ddAutoDir = QtGui.QComboBox(self.centralwidget)
        self.ddAutoDir.setGeometry(QtCore.QRect(580, 11, 51, 20))
        self.ddAutoDir.setObjectName(_fromUtf8("ddAutoDir"))
        self.ddAutoDir.addItem(_fromUtf8(""))
        self.ddAutoDir.addItem(_fromUtf8(""))
        self.lineEdit_9 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(632, 11, 41, 20))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.sbAutoStepInterval = QtGui.QSpinBox(self.centralwidget)
        self.sbAutoStepInterval.setGeometry(QtCore.QRect(670, 11, 42, 20))
        self.sbAutoStepInterval.setMinimum(1)
        self.sbAutoStepInterval.setMaximum(36000)
        self.sbAutoStepInterval.setProperty("value", timeStep)
        self.sbAutoStepInterval.setObjectName(_fromUtf8("sbAutoStepInterval"))
        self.lineEdit_10 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(710, 11, 51, 20))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(550, 70, 91, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.sbAutoVoltageStop = QtGui.QSpinBox(self.centralwidget)
        self.sbAutoVoltageStop.setGeometry(QtCore.QRect(640, 70, 71, 21))
        self.sbAutoVoltageStop.setMaximum(1100)
        self.sbAutoVoltageStop.setSingleStep(1)
        self.sbAutoVoltageStop.setProperty("value", voltStop)
        self.sbAutoVoltageStop.setObjectName(_fromUtf8("sbAutoVoltageStop"))
        self.lineEdit_12 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(550, 40, 91, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.sbAutoMaxCurrent = QtGui.QDoubleSpinBox(self.centralwidget)
        self.sbAutoMaxCurrent.setGeometry(QtCore.QRect(640, 40, 71, 21))
        self.sbAutoMaxCurrent.setMaximum(20000.0)
        self.sbAutoMaxCurrent.setProperty("value", 100.0)
        self.sbAutoMaxCurrent.setObjectName(_fromUtf8("sbAutoMaxCurrent"))
        self.lineEdit_13 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(710, 40, 113, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.cbAutoMaxCurrent = QtGui.QCheckBox(self.centralwidget)
        self.cbAutoMaxCurrent.setGeometry(QtCore.QRect(530, 40, 16, 17))
        self.cbAutoMaxCurrent.setText(_fromUtf8(""))
        self.cbAutoMaxCurrent.setChecked(True)###############
        self.cbAutoMaxCurrent.setObjectName(_fromUtf8("cbAutoMaxCurrent"))
        self.lineEdit_16 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(30, 110, 100, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.cbSetOutDirectory = QtGui.QCheckBox(self.centralwidget)
        self.cbSetOutDirectory.setGeometry(QtCore.QRect(10, 110, 16, 16))
        self.cbSetOutDirectory.setText(_fromUtf8(""))
        self.cbSetOutDirectory.setObjectName(_fromUtf8("cbSetOutDirectory"))
        self.cbSetOutDirectory.setChecked(True)
        self.userOutDirName = QtGui.QTextEdit(self.centralwidget)
        self.userOutDirName.setGeometry(QtCore.QRect(130, 110, 110, 20))
        self.userOutDirName.setObjectName(_fromUtf8("userOutDirName"))  
        self.btnSetSRangeCompliance = QtGui.QCheckBox(self.centralwidget)
        self.btnSetSRangeCompliance.setGeometry(QtCore.QRect(530, 110, 16, 16))
        self.btnSetSRangeCompliance.setText(_fromUtf8(""))
        self.btnSetSRangeCompliance.setObjectName(_fromUtf8("btnSetSRangeCompliance"))
        self.lineEdit_15 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(550, 110, 240, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.cbSetOutFileName = QtGui.QCheckBox(self.centralwidget)
        self.cbSetOutFileName.setGeometry(QtCore.QRect(280, 110, 16, 16))
        self.cbSetOutFileName.setText(_fromUtf8(""))
        self.cbSetOutFileName.setObjectName(_fromUtf8("cbSetOutFileName"))
        self.lineEdit_14 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(300, 110, 110, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.userOutFileName = QtGui.QTextEdit(self.centralwidget)
        self.userOutFileName.setGeometry(QtCore.QRect(410, 110, 110, 20))
        self.userOutFileName.setObjectName(_fromUtf8("userOutFileName"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lineEdit.setText(_translate("MainWindow", "Bias Voltage", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Latest Current Measurement", None))
        self.btnSetVoltage.setText(_translate("MainWindow", "Set Voltage", None))
        self.btnStepUp.setText(_translate("MainWindow", "Step Up", None))
        self.btnStepDown.setText(_translate("MainWindow", "Step Down", None))
        self.lblStepUp.setPlaceholderText(_translate("MainWindow", "to {next_voltage}", None))
        self.lblStepDown.setPlaceholderText(_translate("MainWindow", "to {next_voltage}", None))
        self.lineEdit_5.setText(_translate("MainWindow", "V Step (max 25)", None))
        self.lineEdit_3.setText(_translate("MainWindow", "Measurement Interval [s]", None))
        self.lineEdit_4.setText(_translate("MainWindow", "Plot Refresh Interval [s]", None))
        self.lineEdit_6.setText(_translate("MainWindow", "Current Measurements at Latest Voltage", None))
        self.lineEdit_7.setText(_translate("MainWindow", "All Current Measurements (IV Curve)", None))
        self.label.setText(_translate("MainWindow", "time", None))
        self.label_2.setText(_translate("MainWindow", "voltage", None))
        self.lineEdit_8.setText(_translate("MainWindow", "Step", None))
        self.ddAutoDir.setItemText(0, _translate("MainWindow", "up", None))
        self.ddAutoDir.setItemText(1, _translate("MainWindow", "down", None))
        self.lineEdit_9.setText(_translate("MainWindow", "every", None))
        self.lineEdit_10.setText(_translate("MainWindow", "seconds", None))
        self.lineEdit_11.setText(_translate("MainWindow", "Stop at voltage", None))
        self.lineEdit_12.setText(_translate("MainWindow", "Stop if current >", None))
        self.lineEdit_13.setText(_translate("MainWindow", "microamps(uA)", None))
        self.lineEdit_14.setText(_translate("MainWindow", "Custom Out. F.Name", None))
        self.lineEdit_15.setText(_translate("MainWindow", "Select Source R./Compliance Max t0 20 mA", None))
        self.lineEdit_16.setText(_translate("MainWindow", "Module Output Dir.", None))

